services:
  postgres:
    image: postgres:16.3
    container_name: hack_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "hack"
      POSTGRES_USER: "default"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - hack_postgres_data:/var/lib/postgresql/data
    networks:
      - hack

  superset:
    build: 
      context: .
      dockerfile: Dockerfile_superset
    # image: apache/superset:24b8ffd-ci
    container_name: hack_superset
    restart: unless-stopped
    ports:
      - 127.0.0.1:8088:8088
    environment:
      - SUPERSET_SECRET_KEY=302010
      - OIDC_ENABLE=True
      - DB_DIALECT=sqlite3
    volumes:
      - superset_pythonpath:/app/pythonpath
      - superset_home:/app/superset_home
    networks:
      - hack
    depends_on:
      - postgres

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile_telegram_bot
    image: telegram_bot:latest
    container_name: hack_telegram_bot
    restart: unless-stopped
    networks:
      - hack
    ports:
      - 8000:8000
    depends_on:
      - keycloak
      - postgres
      - superset
    env_file:
      - .telegram_bot.env

  keycloak_postgres:
    image: postgres:16.3
    container_name: keycloak_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_postgres:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KC_HTTP_ENABLED: true
      KC_HTTPS_ENABLED: false
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB_URL: "jdbc:postgresql://keycloak_postgres:5432/keycloak"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak_postgres
    ports:
      - 127.0.0.1:8080:8080

  statistics_server:
    build:
      context: .
      dockerfile: Dockerfile_statistics_server
    image: statistics_server:latest
    container_name: hack_statistics_server
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - hack
    depends_on:
      - postgres
      - superset
    env_file:
      - .statistics_server.env

  opensearch:
    image: opensearchproject/opensearch:1.3.16
    container_name: hack_opensearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - plugins.security.ssl.http.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms2048m -Xmx2048m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch_data:/usr/share/opensearch/data
      # - ./config/config.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/config.yml
      # - ./config/internal_users.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/internal_users.yml
      # - ./config/roles_mapping.yml:/usr/share/opensearch/plugins/opensearch-security/securityconfig/roles_mapping.yml
    ports:
      - 9200:9200
    networks:
      - hack

volumes:
  hack_postgres_data:
  superset_pythonpath:
  superset_home:
  opensearch_data:
  keycloak_postgres:

networks:
  hack:
