FROM python:3.12-slim AS builder

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN rm -rf /app/build/lib /app/build/site-packages/*

FROM builder AS app

WORKDIR /app

COPY ./statistics_server ./src

EXPOSE 5000

CMD ["/bin/bash", "-c", "python3 ./src/app.py"]
