FEATURE_FLAGS = {
	'ENABLE_TEMPLATE_PROCESSING': True,
}

# FEATURE_FLAGS = {
#     "ALERT_REPORTS": True,
#     "DRILL_BY": True,
#     "DRILL_TO_DETAIL": True,
#     "HORIZONTAL_FILTER_BAR": True,
#     "DASHBOARD_CROSS_FILTERS": True,
#     "ENABLE_TEMPLATE_PROCESSING": True,
#     "TAGGING_SYSTEM": True,
#     "HORIZONTAL_FILTER_BAR": True,
#     "ENABLE_EXPLORE_DRAG_AND_DROP": True,
#     "DASHBOARD_RBAC": True,
#     "LISTVIEWS_DEFAULT_CARD_VIEW": True,
# }
